language: objective-c
before_install: gem install xcpretty -N
script:
- cd Example
- set -o pipefail
- xcodebuild -workspace ASCScreenBrightnessDetectorExample.xcworkspace -scheme ASCScreenBrightnessDetectorExample -sdk iphonesimulator test | xcpretty -c
