language: objective-c
before_install: gem install xcpretty -N
script: xcodebuild -workspace Example/ASCScreenBrightnessDetectorExample.xcworkspace -scheme ASCScreenBrightnessDetectorExample -sdk iphonesimulator test | xcpretty -c
